language: c
compiler:
  - gcc
  - clang
env:
  global:
    - prefix=$(pwd)/install
  matrix:
    - DEBUG=0
    - DEBUG=1
before_script:
  - mkdir install
script:
  - ./configure && make install
  - ./configure --enable-maintainer-mode && make install
notifications:
  email:
    recipients:
      - craftik@cyrusian.com
    on_success: always
    on_failure: always
  irc: "irc.ozinger.org#craftIk"
