language: c
compiler:
  - gcc
  - clang
script: touch * && ./configure && make install
notifications:
  email:
    recipients:
      - craftik@cyrusian.com
    on_success: always
    on_failure: always
  irc: "irc.ozinger.org#craftIk"
